name: Windows, MinGW

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32]
        include:
          - arch: x64
            dir: x86_64 
            sys: mingw64
            env: x86_64
          - arch: ia32
            dir: ia32
            sys: mingw32
            env: i686

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          mingw-w64-${{ matrix.env }}-toolchain
          base-devel
          git

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: ./${{ matrix.dir }}/apps/*.efi

  tests:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        arch: [x64, ia32]
        include:
        - arch: x64
          pkg: qemu-system-x86
          qemu_arch: x86_64
          qemu_opts: -M q35
          fw_base: OVMF
        - arch: ia32
          pkg: qemu-system-x86
          qemu_arch: i386
          qemu_opts: -M pc
          fw_base: OVMF

    steps:
    - name: Set up Linux environment
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install ${{ matrix.pkg }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.arch }}

    - name: Download UEFI firmware
      run: |
        fw_arch=$(echo ${{ matrix.arch }} | tr a-z A-Z)
        fw_zip=${{ matrix.fw_base }}-${fw_arch}.zip
        curl -O https://efi.akeo.ie/${{ matrix.fw_base }}/${fw_zip}
        7z x ${fw_zip}
        rm ${fw_zip}

    - name: Download UEFI Shell
      run: |
        curl -L -O https://github.com/pbatard/UEFI-Shell/releases/download/23H2/UEFI-Shell-2.2-23H2-RELEASE.iso
        mkdir ./image
        7z x -o./image *.iso
        rm *.iso

    - name: Run tests
      run: |
         export UEFI_ARCH=${{ matrix.arch }}
         export UEFI_DIR=./image
         export QEMU_CMD="qemu-system-${{ matrix.qemu_arch }} ${{ matrix.qemu_opts }} -L . -drive if=pflash,format=raw,unit=0,file=${{ matrix.fw_base }}.fd,readonly=on -drive format=raw,file=fat:rw:image -nodefaults -nographic -serial stdio -net none"
         ./tests/gen_tests.sh ./tests/test_list.txt
         ./tests/run_tests.sh
